landscaping_erm:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: landscaping-erm
      dataset: erm_dbt
      threads: 4
      timeout_seconds: 300
      location: US
    prod:
      type: bigquery
      method: oauth
      project: landscaping-erm
      dataset: erm_dbt
      threads: 4
      timeout_seconds: 300
      location: US
